project:
  type: book
  output-dir: docs

book:
  title: "openMSE Technical Manual"
  author: "Adrian Hordyk, Quang Huynh, and Tom Carruthers"
  # cover-image: images/openMSE_logo.png
  description: |
    Management Strategy Evaluation with openMSE
  site-url: https://docs.openMSE.com/
  repo-url: https://github.com/blue-matter/openMSETechGuide/
  repo-actions: [edit]
  favicon: images/favicon.png
  date: today

  chapters:
    - index.qmd 
    - overview-manual.qmd
    - part: getting-started.qmd
      chapters:
        - overview-openMSE.qmd  
        - overview-objects.qmd  
        - example-objects.qmd    
        - example-mse.qmd 
    - part: mps-data-advice.qmd
      chapters:
        - object-data.qmd
        - conditioning-obs.qmd
        - generate-data.qmd
        - object-advice.qmd
        - management-procedures.qmd
        - example-mps.qmd    
    - part: developing-oms.qmd
      chapters:
        - om-built-in.qmd  
        - om-import-ss3.qmd
        - om-import-bam.qmd 
        - om-condition-rcm.qmd    
        - om-octopus.qmd
    - part: Concepts
      chapters:
        - concept-schedules.qmd        
        - concept-populate.qmd
        - concept-complexes.qmd
        - concept-seasonal.qmd
        - concept-spatial.qmd
        - concept-ref-points.qmd
        - concept-data-obs.qmd

    - part: Technical Details
      chapters:
        - tech-populate-om.qmd
        - tech-initialize.qmd
        - tech-unfished.qmd

        # - hist_overview.qmd
        # - mp_overview.qmd
        # - mse_overview.qmd
    # - part: walkthrough.qmd
    #   chapters:
    #     - walkthough_hist.qmd
    #     - walkthough_build_mps.qmd
    #     - walkthough_mse.qmd
    # - part: om_build.qmd
    #   chapters:
    #     - build_om.qmd
    #     - build_stock.qmd
    #     - build_fleet.qmd
    #     - build_obs.qmd
    #     - build_om_add_objects.qmd
   # - part: om_condition.qmd
      # chapters:
        # - condition_om.qmd
    #- part: om_import.qmd
      # chapters:
        # - import_om_SS3.qmd
   # - part: om_convert.qmd

    # - part: operatingmodels.qmd
    #   chapters:
    #     - OM_condition.qmd
    #     - OM_import.qmd
    #     - OM_convert.qmd
    # - part: OM_casestudies.qmd
    #   chapters:
    #     - OM_octopus.qmd
    # - part: object_details.qmd
    #   chapters:
    #     - object_advice.qmd
    #     - object_ages.qmd
    #     - object_data.qmd
    #     - object_depletion.qmd
    #     - object_fecundity.qmd
    #     - object_fleet.qmd
    #     - object_hist.qmd
    #     - object_length.qmd
    #     - object_maturity.qmd
    #     - object_naturalmortality.qmd
    #     - object_mse.qmd
    #     - object_om.qmd
    #     - object_spatial.qmd
    #     - object_srr.qmd
    #     - object_stock.qmd
    #     - object_weight.qmd
   # - part: management_procedures.qmd
    #  chapters:
     #   - mps_tac.qmd
    #- part: Eq_overview.qmd
     # chapters:
      #  - Eq_popdynamics.qmd
  appendices:
    - z-app-acknowledgements.qmd
    - z-app-changes_overview.qmd

  sidebar:
    title: 'Technical Manual'
    logo: "images/openMSE_logo.png"
    collapse-level: 1
    tools:
      - icon: globe
        href: https://openMSE.com
        text: "openMSE"
    search: true

format:
  html:
    theme: cosmo
    code-link: true



