# Initialization

## Movement

All openMSE operating models have a spatial dimension. If not specified by the user, this defaults to a 2-area model with very high stock mixing among time-steps - a Markov movement matrix 2 'from' area rows by 2 'to' area columns, with all four transitions set to 0.5. In this configuration the 2-area model almost exactly matches the dynamics of a spatially aggregated model.

If the user wishes to specify some degree of spatial heterogeneity and stock viscosity this is most easily achieved by specifying the time- and age-invariant probability of individuals staying in the first area and the asymptotic fraction of the stock numbers found in area 1. With those two aspects specified it is possible to numerically solve for all values of the 2 x 2 area Markov matrix $\Delta_{t,a,r_{from},r_{to}}$. Since each $r_{from}$ row must sum to 1, there are only two parameters to solve for: $\Delta_{t,a,1,1}$ and $\Delta_{t,a,2,1}$.

These are found by non-linear maximum likelihood estimation using the nlminb() algorithm of R in which finds the values of $\Delta_{t,a,1,1}$ and $\Delta_{t,a,2,1}$ such that $\Delta_{t,a,1,1}$ matches the user specified probability of staying in area 1 and the asymptotic distribution implied by the movement matrix has a fraction of individuals that match user-specified fraction of individuals in area 1.

OpenMSE also allows for using similar non-linear estimation techniques to specify movement matrices for many area models that match a user-specified asymptotic distribution and a mean probability of staying in each area.

## Spatial Distribution

The unfished spatial distribution of numbers by time step and age $D_{t,a}$ is determined by the specified array of movement probabilities $\Delta_{t,a,r_{from},r_{to}}$. The movement matrix for every time and age $\Delta_{t,a}$ is a Markov matrix in which the values in the $r_{from}$ rows sum to 1.

$D$ is calculated numerically. An initialization distribution $D_{I}$ is defined that is homogeneous with the same fraction in each area. I.e., $n_{r}$ elements of value $\frac{1}{n_{r}}$:

$$
D_{I} = [\frac{1}{n_{r}}, \frac{1}{n_{r}}, ... , \frac{1}{n_{r}}]
$$ {#eq-D_init}

For any time step $t$, the distribution of individuals in the first age class ($a=1$) is given by the movement matrix $\Delta$, for that time step and age class :

$$D_{t,1} = D_{I}\Delta_{t,1}$$ {#eq-D_ts}

When calculating $D$ for the first time step, the distribution of individuals in each age class depends on whether a seasonal movement model has been specified or not.

In a non-seasonal model, the distribution in the initial time step is calculated assuming the movement matrix in the first time step occurred in prior time steps:

$$D_{1,a+1} = D_{1,a}\Delta_{1,a+1}$$ {#eq-D_ts1}

In seasonal models the seasonal movement pattern is preserved by assuming the first year ($n_{s}$ time steps) of movements also occurred immediately before the first year:

$$D_{1,a+1} = D_{n_{s},a}\Delta_{1,a+1}$$ {#eq-D_ts1_seas}

For all other time steps ($t>1$) and age classes ($a>1$) the unfished distribution of individuals is given by:

$$D_{t+1,a+1} = D_{t,a}\Delta_{t+1,a+1}$$ {#eq-D}

In this configuration the movement matrix for age class 1 determines the distribution of age class 1 recruits. If the user should wish to distribute these according to some vector of proportions by area, they should put that vector in each of the $r_{from}$ rows for movement in age class 1.

## Unfished Conditions

Natural survival of age-0 fish is assumed to be 100% for all time steps:

$$\zeta_{1,t} = 1$$ {#eq-UC_S_1_0}

In the first time step, survival of older age classes is determined by natural mortality rate $M$, and spawntiming $\varphi_{S}$:

$$\zeta_{a+1,1} = \zeta_{a,1}e^{(-M_{a,1}(1-\varphi_{S})-M_{a+1,1}\varphi_{S})}$$ {#eq-UC_S_1_a}

In subsequent time steps survival is given by:

$$\zeta_{a+1,t+1} = \zeta_{a,t}e^{(-M_{a,t}(1-\varphi_{S})-M_{a+1,t+1}\varphi_{S})}$$ {#eq-UC_S_t_a}

## Age Structure in First Time Step

Age class 1 numbers $N$ in the first time step are calculated from from equilibrium unfished recruitment $R_{0}$ and the recruitment deviation in time step 1 $D_{rec}$:

$$N_{1,1} = R_{0}D_{rec,1}$$ {#eq-AS1_N_0}

For age classes greater than 1, numbers at age in the first time step are calculated from a vector of deviation terms $D_{num}$:

$$N_{a,1} = R_{0}D_{num,a}$$ {#eq-AS1_N_a}

OpenMSE includes tools for solving for user-specified initial stock depletion (spawning biomass in time step 1 relative to unfished, i.e., $\frac{S_{1}}{S_{0}}$).

## Numbers-At-Age 

Rec dev is N0

Na is Z

Move then Z

Numbers at age age are calculated from recruitment


## Semelparous species

# Survival\[,age,1\] \<- Survival\[,age-1,1\] \* exp(-(MLastAge*(1-SpawnTimeFrac)+MThisAge*SpawnTimeFrac)) \* (1-PostSpawnMortalityLastAge)

## Number at Age

### Initial

- annual
- seasonal - initialized to account for seasonal recruitment

Notes:

- age of recruitment is `MinAge(Stock)`
- `MinAge(Stock) == 0` means that recruitment occurs in same time step as `SProduction`
- otherwise lagged by appropriate number of time steps (year, quarters, months)

$$
N_{t+1} = N_t ...
$$
