# Reference Points

fct_Simulate.R - line 38


## Unfished Conditions (fct_CalcUnfishedNumber.R)

Natural survival of age-0 fish is assumed to be 100% for all time steps:

$\zeta_{1,t} = 1$

In the first time step, survival of older age classes is determined by natural mortality rate $M$, and spawntiming $\varphi_{S}$: 

$\zeta_{a+1,1} = \zeta_{a,1}e^{(-M_{a,1}(1-\varphi_{S})-M_{a+1,1}\varphi_{S})}$ 

In subsequent time steps survival is given by: 

$\zeta_{a+1,t+1} = \zeta_{a,t}e^{(-M_{a,t}(1-\varphi_{S})-M_{a+1,t+1}\varphi_{S})}$  

Unfished equilibrium conditions just assume that equilibrium unfished recruitment $R_{0}$ occurs in all years and hence equilibrium unfished numbers at age are calculated as the product of $R_{0}$ and survival $\zeta$: 

$N_{a,t} = R_{0}\zeta_{a,t}$

Unfished (non equilibrium, or 'dynamic') account for variability in recruitment: 

$N_{a,t} = R_{0}\zeta_{a,t}$



## Semelparous species (fct_CalcUnfishedNumber.R)

To be completed

Survival[,age,1] <- Survival[,age-1,1] * exp(-(MLastAge*(1-SpawnTimeFrac)+MThisAge*SpawnTimeFrac)) *
        (1-PostSpawnMortalityLastAge)
