# Primary Objects and Functions

`openMSE` is designed with an object-oriented programming (OOP) paradigm, where the code is organized around **objects**, which contain relevant data, and **functions** (methods) that operate on those objects.

@fig-flowchart shows a conceptual overview of the MSE process in `openMSE`, with colors indicating the primary [**objects**]{style="background:#21b0fe;"} and the [**functions**]{style="background:#fed700;"}.

```{mermaid}
%%| label: fig-flowchart
%%| fig-cap: "An overview of the primary objects and functions used in the MSE process."

flowchart TD
  build([<a href='om_build.html'>Build</a>])
  condition[[<a href='om_condition.html'>Condition</a>]]
  import[[<a href='om_import.html'>Import</a>]]
  convert[[<a href='om_convert.html'>Convert</a>]]
  om[<a href='object_om.html'>OM</a>]
  build:::process --> om
  condition:::function --> om
  import:::function --> om
  convert:::function --> om
  sim[[<a href='walkthrough_hist.html'>Simulate</a>]]
  om:::object --> sim:::function
  hist[<a href='object_hist.html'>Hist</a>]
  sim --> hist:::object
  mp[[<a href='management_procedures.html'>MP</a>]]
  data[<a href='object_data.html'>Data</a>]
  data:::object --> mp
  project[[<a href='object_mse.html'>Project</a>]]
  hist:::object --> project:::function
  mp:::function --> project
  mse[<a href='object_mse.html'>MSE</a>]
  project --> mse:::object


classDef process fill:#fe218b, stroke:#111,stroke-width:1px, color:#000
classDef function fill:#fed700, stroke:#111,stroke-width:1px, color:#000
classDef object fill:#21b0fe, stroke:#111,stroke-width:1px, color:#000

```

## The `OM` Object

The Operating Model (`OM`) object is the main component of the MSE framework. It describes the characteristics of a fishery system and contains all the information required to simulate the population and fleet dynamics, the collection of fishery data, and the application of a management procedure.

`OM` objects can be constructed using one of the following methods:

1.  [**Build**](om_build.html): a process rather than a single function, this method involves creating a new `OM` object, and manually populating the various elements of the object using a combination of expert judgement and available fishery data.
2.  [**Condition**](om_condition.html): generate an `OM` by fitting a fishery population dynamics model to time-series fishery data (e.g., historical catches, indices of abundance, age and/or length compositions).
3.  [**Import**](om_import.html): import an `OM` from the output of an age-structured stock assessment.
4.  [**Convert**](om_convert.html)**:** convert `OM` objectsthat were created in earlier versions of openMSE (see @sec-openmse) to the new object structure developed in openMSE 2.0.

@sec-object_om describes the `OM` object in more detail.

## The `Hist` Object

`Hist` objects are created by applying the `Simulate` function to `OM` objects (@fig-flowchart). These objects contain the simulated historical fishery dynamics and are used to project the model forward in time under a range of different management policies (i.e., management procedures).

@sec-object_hist describes the `Hist` object in more detail.

## The `Data` Object

`Data` objects contain the fishery data that can be used by management procedures (`MP`s) to generate management advice. This fishery data can either be real observed data (primarily for the historical period described in the `Hist` object) or simulated data generated by the model.

@sec-object_data describes the `Data` object in more detail.

## Management Procedure (`MP`) Functions

A Management Procedures (`MP`) is a set of rules which define how a fishery will be managed. These rules can range from simple harvest policies to more complex arrangements.

In `openMSE`, MPs are defined as special R functions that take a `Data` object as the primary argument, and return an `Advice` object (see @sec-object_advice) that contains the management regulations that will be implemented into the fishery.

See the [Management Procedures](management_procedures.html) section for more details on management procedures.

## The `MSE` Object

`MSE` objects are created by applying the `Project` function to `Hist` objects, together with the management procedure (MP) functions that will be used to provide the management advice that was implemented in the simulated fishery (@fig-flowchart).

`MSE` objects contain the fishery dynamics from both the historical period (`Hist`) and the projection period where the `MPs` were applied.

@sec-object_mse describes the `MSE` object in more detail.

## Demonstration of the MSE Process

The following chapters in this section explore these objects and functions in more detail and provide a demonstration of the MSE process.
