# Prerequisites {.unnumbered}

To use `openMSE` or any of its component packages you must have:

1. A recent version of the R software installed on your machine;
2. While not essential, we highly recommend using an integrated development environment (IDE) such as RStudio;
3. The latest version of `openMSE` and the individual component packages installed.

## Installing R
The R statistical language and environment can be freely downloaded from the [CRAN website](https://cran.r-project.org/) and is available for all operating systems.  Updated versions of R are released frequently, and it is recommended that you have the latest version installed. 

Head to the [CRAN website](https://cran.r-project.org/) to download the latest version of R. 

You can check your version of R by typing `version` into the R console.

## Installing RStudio  
[RStudio](https://www.rstudio.com/products/RStudio/) is a freely available integrated development environment (IDE) for R.  It is not essential that you use RStudio, but it can make things a lot easier, especially if you are new to R. 

We assume throughout the `openMSE` documentation that you are using RStudio.  

It is important to be aware that RStudio and R are two different pieces of software that must be installed separately.  We recommend installing the R software before downloading and installing RStudio. 



